### ISSUE TITLE
Error When using with globally installed babel

### ISSUE THREAD

**Issue by hleumas** [vacuumlabs/babel-plugin-extensible-destructuring#2]
```
> babel pokus.js 
/Users/samuel/biznis/clients/ext-dest/node_modules/babel-plugin-extensible-destructuring/lib/index.js:345
	return new Plugin("extensible-destructuring", {
	       ^
TypeError: undefined is not a function
    at module.exports (/Users/samuel/biznis/clients/ext-dest/node_modules/babel-plugin-extensible-destructuring/lib/index.js:345:9)
    at Function.memoisePluginContainer (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/plugin-manager.js:46:23)
    at PluginManager.add (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/plugin-manager.js:130:30)
    at File.buildTransformers (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:281:21)
    at new File (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:148:10)
    at TransformerPipeline.transform (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/transformer-pipeline.js:87:16)
    at Object.exports.transform (/usr/local/lib/node_modules/babel/bin/babel/util.js:33:22)
    at Object.exports.compile (/usr/local/lib/node_modules/babel/bin/babel/util.js:41:18)
    at /usr/local/lib/node_modules/babel/bin/babel/file.js:120:23
    at arrayEach (/usr/local/lib/node_modules/babel/node_modules/lodash/index.js:1314:13)
```

**Comment by hleumas** [comment]
But this works:

`node_modules/babel/bin/babel.js pokus.js`

**Comment by hleumas** [comment]
Upgrade babel to `5.8.`
