### ISSUE TITLE
Support for Babel 7

### ISSUE THREAD

**Issue by dagstuan** [vacuumlabs/babel-plugin-extensible-destructuring#22]
Hello,

The plugin doesnt currently seem to support babel 7, since it should be going stable soon maybe this plugin should implement support for it?

Currently I'm getting errors such as this one in the console when trying to build with babel 7:

```
Module build failed: TypeError: Cannot read property 'name' of undefined
    at DestructuringTransformer.pushObjectProperty (C:\...\node_modules\babel-plugin-extensible-destructuring\lib\index.js:198:96)
    at DestructuringTransformer.pushObjectPattern (C:\...\node_modules\babel-plugin-extensible-destructuring\lib\index.js:240:18)
    at DestructuringTransformer.push (C:\...\node_modules\babel-plugin-extensible-destructuring\lib\index.js:145:16)
...
```

**Comment by hleumas** [comment]
Yeah, you are right. Feel free to submit PR.

**Comment by palnes** [comment]
I've created a PR at #23 that shims the changes in Babel 7. The error above, IIRC, might be related to a change in the Babel plugin `@babel/plugin-transform-react-display-name`.

**Comment by hleumas** [comment]
Thank you! I've merged your PR.

**Comment by michaelmitchell** [comment]
This PR broke babel 6 for me, rolling back to a version without the PR works

`
TypeError: src/components/AddSeatsCalculator/index.jsx: Cannot read property 'name' of undefined
    at DestructuringTransformer.pushObjectProperty (/usr/src/app/app_modules/autom.io-app-accounts/app/node_modules/babel-plugin-extensible-destructuring/lib/index.js:209:96)
    at DestructuringTransformer.pushObjectPattern (/usr/src/app/app_modules/autom.io-app-accounts/app/node_modules/babel-plugin-extensible-destructuring/lib/index.js:251:18)
`

**Comment by palnes** [comment]
yeah, I seem to have gotten it wrong, will submit a second patch. Need to be more thorough. Sorry about this.

**Comment by hleumas** [comment]
Thank you @palnes, I will appreciate a fix from you.

**Comment by hleumas** [comment]
@palnes Are you going to submit a patch please? Otherwise, I would have to revert it to the previous version :(

Appreciate your help!

**Comment by hleumas** [comment]
Reverted to previous version.
