### ISSUE TITLE
Please upgrade to Babel 6

### ISSUE THREAD

**Issue by sean-shirazi** [vacuumlabs/babel-plugin-extensible-destructuring#7]
After upgrading to Babel 6 I get this error message:

/Users/sean/workspace/plumcake-1/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i));
          ^

ReferenceError: Unknown plugin "extensible-destructuring:after" specified in "/Users/sean/workspace/plumcake-1/.babelrc" at 0
    at /Users/sean/workspace/plumcake-1/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/sean/workspace/plumcake-1/node_modules/babel-core/lib/transformation/file/options/option-manager.js:161:20)
    at OptionManager.mergeOptions (/Users/sean/workspace/plumcake-1/node_modules/babel-core/lib/transformation/file/options/option-manager.js:254:36)
    at OptionManager.addConfig (/Users/sean/workspace/plumcake-1/node_modules/babel-core/lib/transformation/file/options/option-manager.js:206:10)
    at OptionManager.findConfigs (/Users/sean/workspace/plumcake-1/node_modules/babel-core/lib/transformation/file/options/option-manager.js:347:16)
    at OptionManager.init (/Users/sean/workspace/plumcake-1/node_modules/babel-core/lib/transformation/file/options/option-manager.js:392:12)
    at compile (/Users/sean/workspace/plumcake-1/node_modules/babel-core/lib/api/register/node.js:96:22)
    at loader (/Users/sean/workspace/plumcake-1/node_modules/babel-core/lib/api/register/node.js:136:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/sean/workspace/plumcake-1/node_modules/babel-core/lib/api/register/node.js:146:7)

**Comment by radiosilence** [comment]
and if you take off the `:after` it still breaks

**Comment by tomaskulich** [comment]
Babel 6 does quite a lot of backward incompatible stuff, so it's no surprise, that the plugin is not working right now. We will need a few days to address this. Stay tuned :)

**Comment by TylorS** [comment]
Looking forward to this :+1:

**Comment by timoly** [comment]
Can you update the npm release and sync the version number between npm and the package.json. 
The current npm release is already 1.0.2

Npm release history: 
'1.0.0': '2015-07-28T07:37:21.797Z',
'1.0.1': '2015-08-02T12:14:53.864Z',
'1.0.2': '2015-08-23T13:17:08.535Z'

**Comment by tomaskulich** [comment]
destructuring 2.0.0 compatible with Babel 6 is on npm now. Happy hacking!
